version: "3.7"

services:
  backend_fastapi:
    container_name: crypto-backend-fastapi-dev
    build: 
      context: ./backendfastapi
      dockerfile: Dockerfile.dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backendfastapi/:/usr/src/app/
    ports:
      - 8000:8000